import type { TemplateFile } from "../file-system.js";
import type { CoreTemplateContext } from "./render.js";
import { coreTokens, renderFiles } from "./render.js";

const productionCoreTemplateFiles: readonly TemplateFile[] = [
	{
		relativePath: "package.json",
		content: `{
	"name": "__PACKAGE_NAME__",
	"version": "0.1.0",
	"private": true,
	"type": "module",
	"scripts": {
		"dev": "next dev --turbo",
		"build": "next build",
		"b": "NEXT_TELEMETRY_DISABLED=1 next build --debug",
		"start": "next start",
		"lint": "biome check --error-on-warnings .",
		"format": "biome check --write .",
		"format:changed": "(git diff --name-only --diff-filter=ACM -z; git diff --cached --name-only --diff-filter=ACM -z) | sort -zu | xargs -0 biome check --write",
		"db:generate": "drizzle-kit generate",
		"db:migrate": "tsx modules/kernel/infrastructure/db/migrate.ts",
		"test": "vitest run --silent=passed-only",
		"test:affected": "vitest run",
		"typecheck": "tsc -p tsconfig.build.json --pretty false --noEmit",
		"lint:sheriff": "sheriff verify",
		"depcruise": "depcruise --config .dependency-cruiser.cjs modules/ app/ components/ hooks/ lib/",
		"dupes": "jscpd",
		"semgrep": "node scripts/run-semgrep.mjs",
		"check": "run-p -n dupes depcruise lint:sheriff semgrep typecheck"
	},
	"dependencies": {
		"drizzle-orm": "^0.45.2",
		"dotenv": "^17.4.2",
		"next": "^16.2.4",
		"postgres": "^3.4.9",
		"react": "^19.2.5",
		"react-dom": "^19.2.5",
		"server-only": "^0.0.1",
		"zod": "^4.3.6"
	},
	"devDependencies": {
		"@biomejs/biome": "^2.4.12",
		"@softarc/sheriff-core": "^0.19.6",
		"@testing-library/jest-dom": "^6.9.1",
		"@testing-library/react": "^16.3.2",
		"@types/node": "^24.12.2",
		"@types/react": "^19.2.14",
		"@types/react-dom": "^19.2.3",
		"dependency-cruiser": "^17.3.10",
		"drizzle-kit": "^0.31.10",
		"jscpd": "^4.0.9",
		"jsdom": "^29.0.2",
		"npm-run-all": "^4.1.5",
		"tsx": "^4.21.0",
		"typescript": "6.0.2",
		"vitest": "^4.1.4"
	},
	"engines": {
		"node": ">=24"
	},
	"packageManager": "pnpm@10.30.2",
	"jscpd": {
		"threshold": 0,
		"reporters": ["markdown"],
		"ignore": [
			"**/node_modules/**",
			"**/.next/**",
			"**/coverage/**",
			"**/tests/**",
			"**/*.json",
			"**/*.tsx",
			"**/*.test.ts",
			"**/*.css",
			"**/*.md"
		]
	}
}
`,
	},
	{
		relativePath: ".trio-generator.json",
		content: `{
	"generator": "create-trio-app",
	"version": "__GENERATOR_VERSION__",
	"preset": "production-core",
	"packageName": "__PACKAGE_NAME__",
	"capabilities": [
		"next-app-router",
		"modular-monolith",
		"drizzle-postgres",
		"admin-shell",
		"architecture-guardrails",
		"vitest"
	]
}
`,
	},
	{
		relativePath: ".gitignore",
		content: `node_modules
.next
dist
coverage
.env
.env.local
report
*.tsbuildinfo
.DS_Store
sheriff-report.json
jscpd-report.md
`,
	},
	{
		relativePath: ".env.example",
		content: `POSTGRES_URL=postgres://postgres:postgres@localhost:5432/__PACKAGE_NAME__
APP_URL=http://localhost:3000
NODE_ENV=development
`,
	},
	{
		relativePath: "README.md",
		content: `# __PROJECT_TITLE__

Generated by \`create-trio-app\` using the production-core preset.

## Commands

\`\`\`sh
pnpm install
pnpm dev
pnpm format:changed && pnpm check && pnpm test:affected
pnpm test && pnpm b
\`\`\`

## Architecture

The project uses a modular monolith with vertical slices under \`modules/*\`.
Dependency direction is \`transport/app -> application -> domain -> ports -> infrastructure\`.
Infrastructure is wired only from \`app/composition\`.

Add a feature module with:

\`\`\`sh
create-trio-app add module billing --project .
\`\`\`
`,
	},
	{
		relativePath: "tsconfig.json",
		content: `{
	"compilerOptions": {
		"target": "esnext",
		"lib": ["dom", "dom.iterable", "esnext"],
		"allowJs": false,
		"skipLibCheck": true,
		"strict": true,
		"noEmit": true,
		"module": "esnext",
		"moduleResolution": "bundler",
		"resolveJsonModule": true,
		"isolatedModules": true,
		"jsx": "react-jsx",
		"incremental": true,
		"noUncheckedIndexedAccess": true,
		"noImplicitReturns": true,
		"noFallthroughCasesInSwitch": true,
		"noUnusedLocals": true,
		"noUnusedParameters": true,
		"noPropertyAccessFromIndexSignature": true,
		"forceConsistentCasingInFileNames": true,
		"verbatimModuleSyntax": true,
		"plugins": [{ "name": "next" }],
		"types": ["node"],
		"paths": {
			"@/*": ["./*"]
		}
	},
	"include": [
		"next-env.d.ts",
		"**/*.ts",
		"**/*.tsx",
		".next/types/**/*.ts",
		".next/dev/types/**/*.ts"
	],
	"exclude": ["node_modules"]
}
`,
	},
	{
		relativePath: "tsconfig.build.json",
		content: `{
	"extends": "./tsconfig.json",
	"exclude": [
		"node_modules",
		"tests",
		"scripts",
		"**/*.test.ts",
		"**/*.test.tsx",
		"**/*.spec.ts",
		"**/*.spec.tsx",
		"vitest.config.ts"
	]
}
`,
	},
	{
		relativePath: "next-env.d.ts",
		content: `/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js and kept in the template so type checks
// work before the first dev server run.
`,
	},
	{
		relativePath: "next.config.ts",
		content: `import type { NextConfig } from "next";
import {
	buildSecurityHeaders,
	resolveSecurityHeadersPolicyForNodeEnv,
} from "./modules/kernel/transport/security-headers";

const nextConfig: NextConfig = {
	typescript: {
		tsconfigPath: "./tsconfig.build.json",
	},
	headers: async () => [
		{
			source: "/:path*",
			headers: buildSecurityHeaders({
				policy: resolveSecurityHeadersPolicyForNodeEnv({
					nodeEnv: process.env["NODE_ENV"],
				}),
				includeCsp: false,
			}),
		},
	],
};

export default nextConfig;
`,
	},
	{
		relativePath: "drizzle.config.ts",
		content: `import { config } from "dotenv";
import { defineConfig } from "drizzle-kit";
import { getPostgresUrl } from "./modules/kernel/config/postgres";

config({ path: ".env.local" });

export default defineConfig({
	schema: "./modules/kernel/infrastructure/db/schema.ts",
	out: "./modules/kernel/infrastructure/db/migrations",
	dialect: "postgresql",
	dbCredentials: {
		url: getPostgresUrl(),
	},
});
`,
	},
	{
		relativePath: "vitest.config.ts",
		content: `import path from "node:path";
import { defineConfig } from "vitest/config";

export default defineConfig({
	resolve: {
		alias: {
			"@": path.resolve(import.meta.dirname, "."),
		},
	},
	test: {
		environment: "jsdom",
		setupFiles: ["./tests/setup.ts"],
		clearMocks: true,
		restoreMocks: true,
		include: ["tests/**/*.test.ts", "tests/**/*.test.tsx"],
		coverage: {
			provider: "v8",
			reporter: ["text", "text-summary", "lcov"],
			exclude: ["tests/**", "node_modules/**"],
		},
	},
});
`,
	},
	{
		relativePath: "biome.jsonc",
		content: `{
	"$schema": "./node_modules/@biomejs/biome/configuration_schema.json",
	"files": {
		"includes": [
			"**",
			"!!**/.next",
			"!!**/node_modules",
			"!!**/coverage",
			"!!modules/kernel/infrastructure/db/migrations"
		]
	},
	"formatter": {
		"enabled": true,
		"formatWithErrors": true,
		"indentStyle": "tab",
		"indentWidth": 2,
		"lineWidth": 80
	},
	"assist": {
		"actions": {
			"source": {
				"organizeImports": "on"
			}
		}
	},
	"linter": {
		"enabled": true,
		"rules": {
			"recommended": true,
			"complexity": {
				"noForEach": "error",
				"noVoid": "error",
				"useDateNow": "error",
				"useOptionalChain": "error",
				"useMaxParams": {
					"level": "error",
					"options": { "max": 5 }
				}
			},
			"correctness": {
				"noUnusedImports": "error",
				"noUnusedVariables": "error",
				"useExhaustiveDependencies": "error"
			},
			"suspicious": {
				"noExplicitAny": "error",
				"noConsole": "off"
			},
			"style": {
				"useImportType": "error",
				"useNodejsImportProtocol": "error"
			}
		}
	}
}
`,
	},
	{
		relativePath: ".dependency-cruiser.cjs",
		content: `/** @type {import('dependency-cruiser').IConfiguration} */
module.exports = {
	forbidden: [
		{
			name: "no-circular",
			severity: "error",
			from: {},
			to: { circular: true },
		},
		{
			name: "not-to-test",
			severity: "error",
			from: { pathNot: "^(tests)" },
			to: { path: "^(tests)" },
		},
		{
			name: "no-infrastructure-in-domain",
			severity: "error",
			from: { path: "^modules/[^/]+/domain/" },
			to: { path: "^modules/[^/]+/infrastructure/" },
		},
		{
			name: "no-infrastructure-in-application",
			severity: "error",
			from: { path: "^modules/[^/]+/application/" },
			to: { path: "^modules/[^/]+/infrastructure/" },
		},
		{
			name: "only-composition-imports-infrastructure",
			severity: "error",
			from: {
				pathNot:
					"^(app/composition/|modules/[^/]+/infrastructure/|tests/)",
			},
			to: { path: "^modules/[^/]+/infrastructure/" },
		},
		{
			name: "no-transport-in-domain",
			severity: "error",
			from: { path: "^modules/[^/]+/domain/" },
			to: { path: "^modules/[^/]+/transport/" },
		},
		{
			name: "no-application-in-domain",
			severity: "error",
			from: { path: "^modules/[^/]+/domain/" },
			to: { path: "^modules/[^/]+/application/" },
		},
		{
			name: "barrel-no-infrastructure-import",
			severity: "error",
			from: { path: "^modules/[^/]+/index.ts$" },
			to: { path: "^modules/[^/]+/infrastructure/" },
		},
		{
			name: "no-nextjs-in-inner-layers",
			severity: "error",
			from: { path: "^modules/[^/]+/(domain|application)/" },
			to: { path: "node_modules/next" },
		},
		{
			name: "sdk-confined-drizzle-orm",
			severity: "error",
			from: {
				path: "^modules/",
				pathNot: ["^modules/[^/]+/infrastructure/", "^modules/kernel/"],
			},
			to: { path: "node_modules/drizzle-orm" },
		},
		{
			name: "sdk-confined-to-kernel-postgres",
			severity: "error",
			from: { pathNot: "^modules/kernel/" },
			to: { path: "node_modules/postgres" },
		},
	],
	options: {
		doNotFollow: { path: "node_modules" },
		tsPreCompilationDeps: true,
		enhancedResolveOptions: {
			exportsFields: ["exports"],
			conditionNames: ["import", "require", "node", "default"],
		},
		reporterOptions: {
			dot: {
				collapsePattern: "node_modules/[^/]+",
			},
		},
	},
};
`,
	},
	{
		relativePath: "semgrep.yml",
		content: `rules:
  - id: no-bare-new-error
    patterns:
      - pattern: new Error(...)
      - pattern-not-inside: "$X instanceof Error ? $X : new Error(String($Y))"
    message: Use domain/application specific errors from the kernel error model.
    languages: [typescript]
    severity: ERROR
    paths:
      exclude:
        - "**/*.test.*"
        - "modules/kernel/domain/errors/**"

  - id: no-console-in-modules
    pattern-either:
      - pattern: console.log(...)
      - pattern: console.warn(...)
      - pattern: console.error(...)
      - pattern: console.info(...)
      - pattern: console.debug(...)
    message: Use createLogger from modules/kernel/observability in module code.
    languages: [typescript]
    severity: ERROR
    paths:
      include:
        - "modules/**"
      exclude:
        - "modules/kernel/observability/**"

  - id: no-process-env-outside-config
    pattern: process.env
    message: Access environment variables through typed config modules.
    languages: [typescript]
    severity: ERROR
    paths:
      include:
        - "modules/**"
      exclude:
        - "**/config/**"
        - "**/config.*"

  - id: no-dynamic-import-in-vitest-tests
    patterns:
      - pattern: await import(...)
      - pattern-either:
          - pattern-inside: |
              it(..., async () => {
                ...
              })
          - pattern-inside: |
              test(..., async () => {
                ...
              })
    message: Use static imports in test files so affected-test discovery can trace dependencies.
    languages: [typescript]
    severity: ERROR
    paths:
      include:
        - "**/*.test.ts"
        - "**/*.test.tsx"
        - "**/*.spec.ts"
        - "**/*.spec.tsx"
`,
	},
	{
		relativePath: "sheriff.config.ts",
		content: `import { type SheriffConfig, sameTag } from "@softarc/sheriff-core";

export const config: SheriffConfig = {
	entryPoints: {
		admin: "./modules/admin/index.ts",
		kernel: "./modules/kernel/index.ts",
		users: "./modules/users/index.ts",
	},
	enableBarrelLess: true,
	modules: {
		"modules/<module>": ["module:<module>", "layer:barrel"],
		"modules/<module>/domain": ["module:<module>", "layer:domain"],
		"modules/<module>/domain/<file>": ["module:<module>", "layer:domain"],
		"modules/<module>/application/ports": ["module:<module>", "layer:ports"],
		"modules/<module>/application/ports/<file>": [
			"module:<module>",
			"layer:ports",
		],
		"modules/<module>/application/use-cases": [
			"module:<module>",
			"layer:use-cases",
		],
		"modules/<module>/application/use-cases/<file>": [
			"module:<module>",
			"layer:use-cases",
		],
		"modules/<module>/application": ["module:<module>", "layer:application"],
		"modules/<module>/application/<area>": [
			"module:<module>",
			"layer:application",
		],
		"modules/<module>/infrastructure": [
			"module:<module>",
			"layer:infrastructure",
		],
		"modules/<module>/infrastructure/<adapter>": [
			"module:<module>",
			"layer:infrastructure",
		],
		"modules/<module>/infrastructure/<adapter>/<file>": [
			"module:<module>",
			"layer:infrastructure",
		],
		"modules/<module>/transport": ["module:<module>", "layer:transport"],
		"modules/<module>/transport/<transport>": [
			"module:<module>",
			"layer:transport",
		],
		"modules/kernel/observability": ["module:kernel", "layer:observability"],
		"modules/kernel/observability/<file>": [
			"module:kernel",
			"layer:observability",
		],
		"modules/<module>/config": ["module:<module>", "layer:config"],
		"modules/<module>/config/<file>": ["module:<module>", "layer:config"],
		lib: "lib",
		"app/composition": "composition",
		app: "app",
		components: "ui",
		hooks: "ui",
	},
	depRules: {
		"module:*": [sameTag, "module:kernel", "layer:barrel", "lib"],
		"layer:barrel": [
			"layer:barrel",
			"layer:domain",
			"layer:ports",
			"layer:use-cases",
			"layer:application",
			"layer:config",
			"layer:transport",
			"layer:observability",
			"lib",
		],
		"layer:domain": ["layer:domain", "layer:barrel", "lib"],
		"layer:ports": ["layer:domain", "layer:barrel", "lib"],
		"layer:use-cases": [
			"layer:domain",
			"layer:barrel",
			"layer:ports",
			"layer:use-cases",
			"layer:application",
			"layer:config",
			"layer:observability",
			"lib",
		],
		"layer:application": [
			"layer:domain",
			"layer:barrel",
			"layer:ports",
			"layer:use-cases",
			"layer:application",
			"layer:config",
			"layer:observability",
			"lib",
		],
		"layer:config": ["layer:domain", "lib"],
		"layer:infrastructure": [
			"layer:domain",
			"layer:barrel",
			"layer:ports",
			"layer:observability",
			"lib",
		],
		"layer:transport": [
			"layer:domain",
			"layer:barrel",
			"layer:ports",
			"layer:use-cases",
			"layer:application",
			"layer:transport",
			"layer:observability",
			"lib",
		],
		"layer:observability": ["layer:domain", "layer:config", "lib"],
		lib: "lib",
		composition: ["module:*", "layer:*", "lib"],
		app: [
			"module:*",
			"layer:barrel",
			"layer:domain",
			"layer:ports",
			"layer:use-cases",
			"layer:application",
			"layer:transport",
			"layer:observability",
			"composition",
			"lib",
			"ui",
		],
		ui: ["ui", "lib", "module:kernel"],
		noTag: ["noTag", "module:*", "layer:*", "lib", "app", "ui", "composition"],
	},
};
`,
	},
	{
		relativePath: "scripts/run-semgrep.mjs",
		content: `import { spawnSync } from "node:child_process";

const result = spawnSync(
	"semgrep",
	["scan", "--config", "semgrep.yml", "--error", "--quiet"],
	{ stdio: "inherit" },
);

if (result.error?.code === "ENOENT") {
	console.warn("[semgrep] semgrep binary not found; install semgrep to enforce semgrep.yml locally.");
	process.exit(0);
}

process.exit(result.status ?? 1);
`,
	},
	{
		relativePath: "app/layout.tsx",
		content: `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
	title: "__PROJECT_TITLE__",
	description: "Generated production-core modular monolith",
};

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	);
}
`,
	},
	{
		relativePath: "app/page.tsx",
		content: `import { Button } from "@/components/ui/button";

export default function HomePage() {
	return (
		<main className="page-shell">
			<section className="hero">
				<p className="eyebrow">Production Core</p>
				<h1>__PROJECT_TITLE__</h1>
				<p className="lede">
					A modular Next.js application with typed boundaries, composition
					roots, tests, and architecture guardrails.
				</p>
				<Button type="button">Ready</Button>
			</section>
		</main>
	);
}
`,
	},
	{
		relativePath: "app/(admin)/admin/page.tsx",
		content: `import { getAdminUseCases } from "@/app/composition/admin";

export default async function AdminPage() {
	const adminUseCases = getAdminUseCases();
	const permissions = await adminUseCases.listPermissionKeys();

	return (
		<main className="page-shell">
			<section className="panel">
				<p className="eyebrow">Admin</p>
				<h1>Admin Shell</h1>
				<p>{permissions.length} permission keys configured.</p>
			</section>
		</main>
	);
}
`,
	},
	{
		relativePath: "app/globals.css",
		content: `:root {
	color-scheme: light;
	font-family:
		Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI",
		sans-serif;
	background: #f6f7f9;
	color: #171923;
}

* {
	box-sizing: border-box;
}

body {
	margin: 0;
	min-height: 100vh;
}

.page-shell {
	min-height: 100vh;
	display: grid;
	align-items: center;
	padding: 48px 24px;
}

.hero,
.panel {
	width: min(720px, 100%);
	margin: 0 auto;
}

.eyebrow {
	margin: 0 0 12px;
	color: #4f46e5;
	font-size: 0.8rem;
	font-weight: 700;
	text-transform: uppercase;
}

h1 {
	margin: 0;
	font-size: clamp(2.5rem, 8vw, 5rem);
	line-height: 0.95;
	letter-spacing: 0;
}

.lede {
	max-width: 600px;
	margin: 24px 0;
	color: #4a5568;
	font-size: 1.125rem;
	line-height: 1.6;
}
`,
	},
	{
		relativePath: "components/ui/button.tsx",
		content: `import type { ButtonHTMLAttributes } from "react";
import { cn } from "./classnames";

export function Button({
	className,
	type,
	...props
}: ButtonHTMLAttributes<HTMLButtonElement>) {
	return (
		<button
			className={cn("ui-button", className)}
			type={type ?? "button"}
			{...props}
		/>
	);
}
`,
	},
	{
		relativePath: "components/ui/classnames.ts",
		content: `export function cn(
	...values: Array<string | false | null | undefined>
): string {
	return values.filter((value): value is string => Boolean(value)).join(" ");
}
`,
	},
	{
		relativePath: "components/shared/browser/fetch.ts",
		content: `export class FetchJsonError extends Error {
	constructor(message: string, readonly status: number) {
		super(message);
		this.name = "FetchJsonError";
	}
}

export async function fetchJson<T>(
	input: RequestInfo | URL,
	parse: (value: unknown) => T,
	init?: RequestInit,
): Promise<T> {
	const response = await fetch(input, init);
	if (!response.ok) {
		throw new FetchJsonError("Request failed", response.status);
	}
	return parse(await response.json());
}
`,
	},
	{
		relativePath: "hooks/use-async-state.ts",
		content: `import { useCallback, useState } from "react";

export type AsyncStatus = "loading" | "success" | "error";

export interface AsyncState<T> {
	status: AsyncStatus;
	data: T | null;
	error: Error | null;
}

interface UseAsyncStateParams<T> {
	initialData?: T | null;
}

interface UseAsyncStateResult<T> {
	state: AsyncState<T>;
	resetLoading: () => void;
	setLoading: () => void;
	setSuccess: (data: T) => void;
	updateSuccess: (update: (currentData: T | null) => T) => void;
	setError: (error: Error) => void;
}

function buildInitialState<T>(params: UseAsyncStateParams<T>): AsyncState<T> {
	if (!Object.hasOwn(params, "initialData") || params.initialData === null) {
		return { status: "loading", data: null, error: null };
	}
	return { status: "success", data: params.initialData ?? null, error: null };
}

export function useAsyncState<T>(
	params: UseAsyncStateParams<T> = {},
): UseAsyncStateResult<T> {
	const [state, setState] = useState<AsyncState<T>>(() =>
		buildInitialState(params),
	);

	const setLoading = useCallback(() => {
		setState((currentState) => ({
			status: "loading",
			data: currentState.data,
			error: null,
		}));
	}, []);

	const resetLoading = useCallback(() => {
		setState({ status: "loading", data: null, error: null });
	}, []);

	const setSuccess = useCallback((data: T) => {
		setState({ status: "success", data, error: null });
	}, []);

	const updateSuccess = useCallback((update: (currentData: T | null) => T) => {
		setState((currentState) => ({
			status: "success",
			data: update(currentState.data),
			error: null,
		}));
	}, []);

	const setError = useCallback((error: Error) => {
		setState((currentState) => ({
			status: "error",
			data: currentState.data,
			error,
		}));
	}, []);

	return {
		state,
		resetLoading,
		setLoading,
		setSuccess,
		updateSuccess,
		setError,
	};
}
`,
	},
	{
		relativePath: "lib/ids/index.ts",
		content: `export function createId(prefix: string): string {
	return [prefix, crypto.randomUUID()].join("_");
}
`,
	},
	{
		relativePath: "modules/kernel/application/ports/cache-policy.ts",
		content: `export interface CachePolicy<TParams, TValue> {
	name: string;
	ttlSeconds: number;
	buildKey: (params: TParams) => string;
	parse: (value: unknown) => TValue;
}
`,
	},
	{
		relativePath: "modules/kernel/application/ports/cache-gateway.ts",
		content: `import type { CachePolicy } from "./cache-policy";

export interface CacheGateway {
	get: <TParams, TValue>(
		policy: CachePolicy<TParams, TValue>,
		params: TParams,
	) => Promise<TValue | undefined>;
	set: <TParams, TValue>(
		policy: CachePolicy<TParams, TValue>,
		params: TParams,
		value: TValue,
	) => Promise<void>;
	delete: <TParams, TValue>(
		policy: CachePolicy<TParams, TValue>,
		params: TParams,
	) => Promise<void>;
}
`,
	},
	{
		relativePath: "modules/kernel/application/ports/clock.ts",
		content: `export interface Clock {
	now: () => Date;
}
`,
	},
	{
		relativePath: "modules/kernel/application/ports/id-generator.ts",
		content: `export interface IdGenerator {
	generate: (prefix: string) => string;
}
`,
	},
	{
		relativePath: "modules/kernel/domain/errors/app-error.ts",
		content: `export interface AppErrorOptions {
	code: string;
	category: "validation" | "not_found" | "forbidden" | "internal";
	details?: Record<string, unknown>;
}

export class AppError extends Error {
	readonly code: string;
	readonly category: AppErrorOptions["category"];
	readonly details: Record<string, unknown> | undefined;

	constructor(message: string, options: AppErrorOptions) {
		super(message);
		this.name = "AppError";
		this.code = options.code;
		this.category = options.category;
		this.details = options.details;
	}
}

export function isAppError(error: unknown): error is AppError {
	return error instanceof AppError;
}
`,
	},
	{
		relativePath: "modules/kernel/domain/errors/validation-error.ts",
		content: `import { AppError } from "./app-error";

export interface ValidationErrorDetails {
	fieldErrors?: Record<string, string[]>;
	formErrors?: string[];
}

export class ValidationError extends AppError {
	readonly validationDetails: ValidationErrorDetails;

	constructor(message: string, details: ValidationErrorDetails = {}) {
		super(message, {
			code: "validation:invalid_input",
			category: "validation",
			details: { validationDetails: details },
		});
		this.name = "ValidationError";
		this.validationDetails = details;
	}
}
`,
	},
	{
		relativePath: "modules/kernel/domain/errors/internal-error.ts",
		content: `import { AppError } from "./app-error";

export class InternalError extends AppError {
	constructor(message: string, details?: Record<string, unknown>) {
		super(message, {
			code: "internal:unexpected",
			category: "internal",
			details,
		});
		this.name = "InternalError";
	}
}
`,
	},
	{
		relativePath: "modules/kernel/domain/errors/database-error.ts",
		content: `import { AppError } from "./app-error";

export class DatabaseError extends AppError {
	constructor(message: string, details?: Record<string, unknown>) {
		super(message, {
			code: "internal:database",
			category: "internal",
			details,
		});
		this.name = "DatabaseError";
	}
}

export function createDatabaseError(
	operation: string,
	error: unknown,
	context: Record<string, unknown> = {},
): DatabaseError {
	return new DatabaseError("Database operation failed", {
		operation,
		error: error instanceof Error ? error.message : String(error),
		...context,
	});
}
`,
	},
	{
		relativePath: "modules/kernel/domain/errors/index.ts",
		content: `import { AppError } from "./app-error";

export {
	AppError,
	type AppErrorOptions,
	isAppError,
} from "./app-error";
export {
	createDatabaseError,
	DatabaseError,
} from "./database-error";
export { InternalError } from "./internal-error";
export {
	ValidationError,
	type ValidationErrorDetails,
} from "./validation-error";

export function createAppErrorFromCode(
	code: string,
	details?: Record<string, unknown>,
): AppError {
	const category = code.startsWith("not_found:")
		? "not_found"
		: code.startsWith("forbidden:")
			? "forbidden"
			: code.startsWith("validation:")
				? "validation"
				: "internal";
	return new AppError("Application error", { code, category, details });
}
`,
	},
	{
		relativePath: "modules/kernel/domain/index.ts",
		content: `export {
	AppError,
	type AppErrorOptions,
	createAppErrorFromCode,
	createDatabaseError,
	DatabaseError,
	InternalError,
	isAppError,
	ValidationError,
	type ValidationErrorDetails,
} from "./errors";
`,
	},
	{
		relativePath: "modules/kernel/config/environment.ts",
		content: `export const nodeEnv = process.env["NODE_ENV"] ?? "development";

export function isProduction(): boolean {
	return nodeEnv === "production";
}
`,
	},
	{
		relativePath: "modules/kernel/config/postgres.ts",
		content: `import { InternalError } from "../domain";
import { z } from "zod";
import { isProduction } from "./environment";

const postgresUrlSchema = z.string().url();

export function getPostgresUrl(): string {
	const value = process.env["POSTGRES_URL"];
	if (value !== undefined && value.length > 0) {
		return postgresUrlSchema.parse(value);
	}
	if (isProduction()) {
		throw new InternalError("POSTGRES_URL is required in production");
	}
	return "postgres://postgres:postgres@localhost:5432/app";
}
`,
	},
	{
		relativePath: "modules/kernel/observability/logger.ts",
		content: `export interface LogFields {
	event: string;
	error?: string;
	details?: Record<string, unknown>;
}

export interface Logger {
	debug: (fields: LogFields) => void;
	info: (fields: LogFields) => void;
	warn: (fields: LogFields) => void;
	error: (fields: LogFields) => void;
}

export function createLogger(scope: string): Logger {
	return {
		debug: (fields) => writeLog("debug", scope, fields),
		info: (fields) => writeLog("info", scope, fields),
		warn: (fields) => writeLog("warn", scope, fields),
		error: (fields) => writeLog("error", scope, fields),
	};
}

function writeLog(
	level: "debug" | "info" | "warn" | "error",
	scope: string,
	fields: LogFields,
): void {
	console[level](JSON.stringify({ level, scope, ...fields }));
}
`,
	},
	{
		relativePath: "modules/kernel/observability/index.ts",
		content: `export {
	createLogger,
	type Logger,
	type LogFields,
} from "./logger";
`,
	},
	{
		relativePath: "modules/kernel/transport/http-response.ts",
		content: `export function jsonResponse<T>(body: T, init?: ResponseInit): Response {
	return Response.json(body, init);
}
`,
	},
	{
		relativePath: "modules/kernel/transport/http-error-mapper.ts",
		content: `import { isAppError } from "../domain";

export function statusForError(error: unknown): number {
	if (!isAppError(error)) {
		return 500;
	}
	if (error.category === "validation") {
		return 400;
	}
	if (error.category === "not_found") {
		return 404;
	}
	if (error.category === "forbidden") {
		return 403;
	}
	return 500;
}
`,
	},
	{
		relativePath: "modules/kernel/transport/security-headers.ts",
		content: `export interface SecurityHeadersPolicy {
	frameAncestors: "none" | "self";
}

export function resolveSecurityHeadersPolicyForNodeEnv(params: {
	nodeEnv?: string | undefined;
}): SecurityHeadersPolicy {
	return {
		frameAncestors: params.nodeEnv === "development" ? "self" : "none",
	};
}

export function buildSecurityHeaders(params: {
	policy: SecurityHeadersPolicy;
	includeCsp: boolean;
}): Array<{ key: string; value: string }> {
	const headers = [
		{ key: "X-Content-Type-Options", value: "nosniff" },
		{ key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
		{ key: "X-Frame-Options", value: "DENY" },
	];
	if (!params.includeCsp) {
		return headers;
	}
	return [
		...headers,
		{
			key: "Content-Security-Policy",
			value: "frame-ancestors " + params.policy.frameAncestors,
		},
	];
}
`,
	},
	{
		relativePath: "modules/kernel/transport/index.ts",
		content: `export { jsonResponse } from "./http-response";
export { statusForError } from "./http-error-mapper";
export {
	buildSecurityHeaders,
	resolveSecurityHeadersPolicyForNodeEnv,
	type SecurityHeadersPolicy,
} from "./security-headers";
`,
	},
	{
		relativePath: "modules/kernel/infrastructure/db/schema.ts",
		content: `import { pgTable, timestamp, uuid, varchar } from "drizzle-orm/pg-core";

export const user = pgTable("User", {
	id: uuid("id").primaryKey().notNull().defaultRandom(),
	name: varchar("name", { length: 128 }).notNull(),
	email: varchar("email", { length: 256 }).notNull().unique(),
	createdAt: timestamp("createdAt").notNull().defaultNow(),
});

export const adminActionPermission = pgTable("AdminActionPermission", {
	id: uuid("id").primaryKey().notNull().defaultRandom(),
	userId: uuid("userId")
		.notNull()
		.references(() => user.id, { onDelete: "cascade" }),
	permissionKey: varchar("permissionKey", { length: 128 }).notNull(),
	grantedAt: timestamp("grantedAt").notNull().defaultNow(),
});
`,
	},
	{
		relativePath: "modules/kernel/infrastructure/db/index.ts",
		content: `import { drizzle } from "drizzle-orm/postgres-js";
import postgres from "postgres";
import { getPostgresUrl } from "../../config/postgres";
import * as schema from "./schema";

function createDb() {
	const client = postgres(getPostgresUrl(), { prepare: false });
	return drizzle(client, { schema });
}

export type Db = ReturnType<typeof createDb>;

let cachedDb: Db | undefined;

export function getDb(): Db {
	cachedDb ??= createDb();
	return cachedDb;
}
`,
	},
	{
		relativePath: "modules/kernel/infrastructure/db/types.ts",
		content: `import type { Db } from "./index";

export type DbLike = Db;
`,
	},
	{
		relativePath: "modules/kernel/infrastructure/db/migrate.ts",
		content: `import { migrate } from "drizzle-orm/postgres-js/migrator";
import { getDb } from "./index";

await migrate(getDb(), {
	migrationsFolder: "modules/kernel/infrastructure/db/migrations",
});
`,
	},
	{
		relativePath: "modules/kernel/infrastructure/db/migrations/.gitkeep",
		content: "",
	},
	{
		relativePath: "modules/kernel/index.ts",
		content: `export type { CacheGateway } from "./application/ports/cache-gateway";
export type { CachePolicy } from "./application/ports/cache-policy";
export type { Clock } from "./application/ports/clock";
export type { IdGenerator } from "./application/ports/id-generator";
export {
	AppError,
	type AppErrorOptions,
	createAppErrorFromCode,
	createDatabaseError,
	DatabaseError,
	InternalError,
	isAppError,
	ValidationError,
	type ValidationErrorDetails,
} from "./domain";
export {
	createLogger,
	type Logger,
	type LogFields,
} from "./observability";
export {
	jsonResponse,
	statusForError,
} from "./transport";
`,
	},
	{
		relativePath: "modules/users/domain/user.ts",
		content: `import { z } from "zod";

export const userIdSchema = z.string().uuid().brand<"UserId">();
export const userEmailSchema = z.string().email().brand<"UserEmail">();

export type UserId = z.infer<typeof userIdSchema>;
export type UserEmail = z.infer<typeof userEmailSchema>;

export interface User {
	id: UserId;
	name: string;
	email: UserEmail;
	createdAt: Date;
}

export function asUserId(value: string): UserId {
	return userIdSchema.parse(value);
}

export function asUserEmail(value: string): UserEmail {
	return userEmailSchema.parse(value);
}
`,
	},
	{
		relativePath: "modules/users/domain/index.ts",
		content: `export {
	asUserEmail,
	asUserId,
	type User,
	type UserEmail,
	type UserId,
	userEmailSchema,
	userIdSchema,
} from "./user";
`,
	},
	{
		relativePath: "modules/users/application/ports/user-repository.ts",
		content: `import type { User, UserEmail, UserId } from "../../domain";

export interface CreateUserParams {
	name: string;
	email: UserEmail;
}

export interface UserRepository {
	create: (params: CreateUserParams) => Promise<User>;
	getById: (id: UserId) => Promise<User | undefined>;
	getByEmail: (email: UserEmail) => Promise<User | undefined>;
}
`,
	},
	{
		relativePath: "modules/users/application/use-cases/create-user.ts",
		content: `import type { User } from "../../domain";
import { asUserEmail } from "../../domain";
import type {
	CreateUserParams,
	UserRepository,
} from "../ports/user-repository";

export interface CreateUserDependencies {
	userRepository: UserRepository;
}

export function createCreateUser(dependencies: CreateUserDependencies) {
	return async function createUser(params: {
		name: string;
		email: string;
	}): Promise<User> {
		const createParams: CreateUserParams = {
			name: params.name.trim(),
			email: asUserEmail(params.email),
		};
		return await dependencies.userRepository.create(createParams);
	};
}
`,
	},
	{
		relativePath: "modules/users/application/use-cases/get-user-by-id.ts",
		content: `import { createAppErrorFromCode } from "@/modules/kernel/domain";
import type { User, UserId } from "../../domain";
import type { UserRepository } from "../ports/user-repository";

export interface GetUserByIdDependencies {
	userRepository: UserRepository;
}

export function createGetUserById(dependencies: GetUserByIdDependencies) {
	return async function getUserById(id: UserId): Promise<User> {
		const user = await dependencies.userRepository.getById(id);
		if (!user) {
			throw createAppErrorFromCode("not_found:user");
		}
		return user;
	};
}
`,
	},
	{
		relativePath: "modules/users/factory.ts",
		content: `import type { UserRepository } from "./application/ports/user-repository";
import { createCreateUser } from "./application/use-cases/create-user";
import { createGetUserById } from "./application/use-cases/get-user-by-id";

export interface UserUseCases {
	createUser: ReturnType<typeof createCreateUser>;
	getUserById: ReturnType<typeof createGetUserById>;
}

export interface UserUseCaseDependencies {
	userRepository: UserRepository;
}

export function createUserUseCases(
	dependencies: UserUseCaseDependencies,
): UserUseCases {
	return {
		createUser: createCreateUser({
			userRepository: dependencies.userRepository,
		}),
		getUserById: createGetUserById({
			userRepository: dependencies.userRepository,
		}),
	};
}
`,
	},
	{
		relativePath: "modules/users/index.ts",
		content: `export type {
	CreateUserParams,
	UserRepository,
} from "./application/ports/user-repository";
export {
	createCreateUser,
	type CreateUserDependencies,
} from "./application/use-cases/create-user";
export {
	createGetUserById,
	type GetUserByIdDependencies,
} from "./application/use-cases/get-user-by-id";
export {
	asUserEmail,
	asUserId,
	type User,
	type UserEmail,
	type UserId,
	userEmailSchema,
	userIdSchema,
} from "./domain";
export {
	createUserUseCases,
	type UserUseCaseDependencies,
	type UserUseCases,
} from "./factory";
`,
	},
	{
		relativePath:
			"modules/users/infrastructure/drizzle/user-repository-drizzle.ts",
		content: `import { eq } from "drizzle-orm";
import { createDatabaseError } from "@/modules/kernel/domain";
import { getDb } from "@/modules/kernel/infrastructure/db";
import { user } from "@/modules/kernel/infrastructure/db/schema";
import type { DbLike } from "@/modules/kernel/infrastructure/db/types";
import type { User } from "../../domain";
import { asUserEmail, asUserId } from "../../domain";
import type {
	UserRepository,
} from "../../application/ports/user-repository";

export interface UserRepositoryDependencies {
	db?: DbLike;
}

export function createUserRepository(
	dependencies: UserRepositoryDependencies = {},
): UserRepository {
	return {
		create: async (params) => {
			const database = dependencies.db ?? getDb();
			try {
				const [row] = await database
					.insert(user)
					.values({ name: params.name, email: params.email })
					.returning();
				return mapUserRow(row);
			} catch (error) {
				throw createDatabaseError("users.create", error, {
					email: params.email,
				});
			}
		},
		getById: async (id) => {
			const database = dependencies.db ?? getDb();
			const rows = await database
				.select()
				.from(user)
				.where(eq(user.id, id))
				.limit(1);
			return rows[0] ? mapUserRow(rows[0]) : undefined;
		},
		getByEmail: async (email) => {
			const database = dependencies.db ?? getDb();
			const rows = await database
				.select()
				.from(user)
				.where(eq(user.email, email))
				.limit(1);
			return rows[0] ? mapUserRow(rows[0]) : undefined;
		},
	};
}

function mapUserRow(row: typeof user.$inferSelect | undefined): User {
	if (!row) {
		throw createDatabaseError("users.map", "Missing row");
	}
	return {
		id: asUserId(row.id),
		name: row.name,
		email: asUserEmail(row.email),
		createdAt: row.createdAt,
	};
}
`,
	},
	{
		relativePath: "modules/admin/domain/permissions.ts",
		content: `import { z } from "zod";

export const PERMISSION_KEYS = {
	ADMIN_READ: "admin:read",
	ADMIN_WRITE: "admin:write",
	USERS_READ: "admin:users:read",
	USERS_WRITE: "admin:users:write",
} as const;

export const permissionKeySchema = z.enum([
	PERMISSION_KEYS.ADMIN_READ,
	PERMISSION_KEYS.ADMIN_WRITE,
	PERMISSION_KEYS.USERS_READ,
	PERMISSION_KEYS.USERS_WRITE,
]);

export type PermissionKey = z.infer<typeof permissionKeySchema>;
`,
	},
	{
		relativePath: "modules/admin/domain/index.ts",
		content: `export {
	PERMISSION_KEYS,
	type PermissionKey,
	permissionKeySchema,
} from "./permissions";
`,
	},
	{
		relativePath:
			"modules/admin/application/ports/admin-permission-repository.ts",
		content: `import type { UserId } from "@/modules/users";
import type { PermissionKey } from "../../domain";

export interface AdminPermissionRepository {
	listPermissionKeys: () => Promise<PermissionKey[]>;
	userHasPermission: (params: {
		userId: UserId;
		permissionKey: PermissionKey;
	}) => Promise<boolean>;
}
`,
	},
	{
		relativePath: "modules/admin/application/use-cases/list-permission-keys.ts",
		content: `import type { PermissionKey } from "../../domain";
import type { AdminPermissionRepository } from "../ports/admin-permission-repository";

export interface ListPermissionKeysDependencies {
	adminPermissionRepository: AdminPermissionRepository;
}

export function createListPermissionKeys(
	dependencies: ListPermissionKeysDependencies,
) {
	return async function listPermissionKeys(): Promise<PermissionKey[]> {
		return await dependencies.adminPermissionRepository.listPermissionKeys();
	};
}
`,
	},
	{
		relativePath:
			"modules/admin/application/use-cases/assert-admin-permission.ts",
		content: `import { createAppErrorFromCode } from "@/modules/kernel/domain";
import type { UserId } from "@/modules/users";
import type { PermissionKey } from "../../domain";
import type { AdminPermissionRepository } from "../ports/admin-permission-repository";

export interface AssertAdminPermissionDependencies {
	adminPermissionRepository: AdminPermissionRepository;
}

export function createAssertAdminPermission(
	dependencies: AssertAdminPermissionDependencies,
) {
	return async function assertAdminPermission(params: {
		userId: UserId;
		permissionKey: PermissionKey;
	}): Promise<void> {
		const permitted =
			await dependencies.adminPermissionRepository.userHasPermission(params);
		if (!permitted) {
			throw createAppErrorFromCode("forbidden:admin_permission", {
				permissionKey: params.permissionKey,
			});
		}
	};
}
`,
	},
	{
		relativePath: "modules/admin/factory.ts",
		content: `import type { AdminPermissionRepository } from "./application/ports/admin-permission-repository";
import { createAssertAdminPermission } from "./application/use-cases/assert-admin-permission";
import { createListPermissionKeys } from "./application/use-cases/list-permission-keys";

export interface AdminUseCases {
	assertAdminPermission: ReturnType<typeof createAssertAdminPermission>;
	listPermissionKeys: ReturnType<typeof createListPermissionKeys>;
}

export interface AdminUseCaseDependencies {
	adminPermissionRepository: AdminPermissionRepository;
}

export function createAdminUseCases(
	dependencies: AdminUseCaseDependencies,
): AdminUseCases {
	return {
		assertAdminPermission: createAssertAdminPermission({
			adminPermissionRepository: dependencies.adminPermissionRepository,
		}),
		listPermissionKeys: createListPermissionKeys({
			adminPermissionRepository: dependencies.adminPermissionRepository,
		}),
	};
}
`,
	},
	{
		relativePath: "modules/admin/index.ts",
		content: `export type { AdminPermissionRepository } from "./application/ports/admin-permission-repository";
export {
	createAssertAdminPermission,
	type AssertAdminPermissionDependencies,
} from "./application/use-cases/assert-admin-permission";
export {
	createListPermissionKeys,
	type ListPermissionKeysDependencies,
} from "./application/use-cases/list-permission-keys";
export {
	PERMISSION_KEYS,
	type PermissionKey,
	permissionKeySchema,
} from "./domain";
export {
	createAdminUseCases,
	type AdminUseCaseDependencies,
	type AdminUseCases,
} from "./factory";
`,
	},
	{
		relativePath:
			"modules/admin/infrastructure/drizzle/admin-permission-repository-drizzle.ts",
		content: `import { and, eq } from "drizzle-orm";
import { getDb } from "@/modules/kernel/infrastructure/db";
import { adminActionPermission } from "@/modules/kernel/infrastructure/db/schema";
import type { DbLike } from "@/modules/kernel/infrastructure/db/types";
import {
	PERMISSION_KEYS,
	permissionKeySchema,
} from "../../domain";
import type { AdminPermissionRepository } from "../../application/ports/admin-permission-repository";

export interface AdminPermissionRepositoryDependencies {
	db?: DbLike;
}

export function createAdminPermissionRepository(
	dependencies: AdminPermissionRepositoryDependencies = {},
): AdminPermissionRepository {
	return {
		listPermissionKeys: async () => Object.values(PERMISSION_KEYS),
		userHasPermission: async (params) => {
			const database = dependencies.db ?? getDb();
			const rows = await database
				.select({ permissionKey: adminActionPermission.permissionKey })
				.from(adminActionPermission)
				.where(
					and(
						eq(adminActionPermission.userId, params.userId),
						eq(adminActionPermission.permissionKey, params.permissionKey),
					),
				)
				.limit(1);
			return rows.some((row) =>
				permissionKeySchema.safeParse(row.permissionKey).success,
			);
		},
	};
}
`,
	},
	{
		relativePath: "app/composition/shared/singleton.ts",
		content: `import "server-only";

type AssertSync<T> = T extends Promise<unknown> ? never : T;

function hasOverrides<O>(overrides: O | undefined): overrides is O {
	return (
		overrides !== undefined &&
		overrides !== null &&
		typeof overrides === "object" &&
		Object.keys(overrides).length > 0
	);
}

export function createCachedFactory<T, O>(
	create: (overrides?: O | undefined) => AssertSync<T>,
): (overrides?: O | undefined) => T {
	let cached: T | undefined;

	return (overrides?: O | undefined) => {
		if (hasOverrides(overrides)) {
			return create(overrides);
		}
		if (!cached) {
			cached = create();
		}
		return cached;
	};
}
`,
	},
	{
		relativePath: "app/composition/clock.ts",
		content: `import "server-only";

import type { Clock } from "@/modules/kernel";

export function getDefaultClock(): Clock {
	return {
		now: () => new Date(),
	};
}
`,
	},
	{
		relativePath: "app/composition/id-generator.ts",
		content: `import "server-only";

import type { IdGenerator } from "@/modules/kernel";
import { createId } from "@/lib/ids";

export function getDefaultIdGenerator(): IdGenerator {
	return {
		generate: createId,
	};
}
`,
	},
	{
		relativePath: "app/composition/observability.ts",
		content: `import "server-only";

import { createLogger } from "@/modules/kernel";

export function getObservability() {
	return {
		createLogger,
	};
}
`,
	},
	{
		relativePath: "app/composition/users.ts",
		content: `import "server-only";

import {
	createUserUseCases,
	type UserRepository,
	type UserUseCases,
} from "@/modules/users";
import { createUserRepository } from "@/modules/users/infrastructure/drizzle/user-repository-drizzle";
import { createCachedFactory } from "./shared/singleton";

export interface UserUseCaseOverrides {
	userRepository?: UserRepository;
}

function createUserUseCasesWithDefaults(
	overrides: UserUseCaseOverrides = {},
): UserUseCases {
	return createUserUseCases({
		userRepository: overrides.userRepository ?? createUserRepository(),
	});
}

export const getUserUseCases = createCachedFactory<
	UserUseCases,
	UserUseCaseOverrides
>(createUserUseCasesWithDefaults);
`,
	},
	{
		relativePath: "app/composition/admin.ts",
		content: `import "server-only";

import {
	createAdminUseCases,
	type AdminPermissionRepository,
	type AdminUseCases,
	PERMISSION_KEYS,
} from "@/modules/admin";
import { createAdminPermissionRepository } from "@/modules/admin/infrastructure/drizzle/admin-permission-repository-drizzle";
import { createCachedFactory } from "./shared/singleton";

export interface AdminUseCaseOverrides {
	adminPermissionRepository?: AdminPermissionRepository;
}

function createAdminUseCasesWithDefaults(
	overrides: AdminUseCaseOverrides = {},
): AdminUseCases {
	return createAdminUseCases({
		adminPermissionRepository:
			overrides.adminPermissionRepository ??
			createAdminPermissionRepository(),
	});
}

export const getAdminUseCases = createCachedFactory<
	AdminUseCases,
	AdminUseCaseOverrides
>(createAdminUseCasesWithDefaults);

export function getDefaultAdminPermissionKeys() {
	return Object.values(PERMISSION_KEYS);
}
`,
	},
	{
		relativePath: "app/admin/actions/auth-utils.ts",
		content: `import { isAppError } from "@/modules/kernel";

export interface ActionSuccess<T> {
	success: true;
	data: T;
}

export interface ActionFailure {
	success: false;
	error: string;
	code?: string;
}

export type ActionResult<T> = ActionSuccess<T> | ActionFailure;

export async function withAdminAction<T>(
	action: () => Promise<T>,
): Promise<ActionResult<T>> {
	try {
		return {
			success: true,
			data: await action(),
		};
	} catch (error) {
		return {
			success: false,
			error: error instanceof Error ? error.message : String(error),
			code: isAppError(error) ? error.code : undefined,
		};
	}
}
`,
	},
	{
		relativePath: "app/admin/actions/users/create-user-action.ts",
		content: `"use server";

import { getUserUseCases } from "@/app/composition/users";
import { withAdminAction } from "../auth-utils";

export async function createUserAction(params: {
	name: string;
	email: string;
}) {
	return await withAdminAction(async () => {
		const useCases = getUserUseCases();
		return await useCases.createUser(params);
	});
}
`,
	},
	{
		relativePath: "tests/setup.ts",
		content: `import "@testing-library/jest-dom/vitest";
import { vi } from "vitest";

vi.mock("server-only", () => ({}));
`,
	},
	{
		relativePath: "tests/app/composition/shared/singleton.test.ts",
		content: `import { describe, expect, it, vi } from "vitest";
import { createCachedFactory } from "@/app/composition/shared/singleton";

describe("createCachedFactory", () => {
	it("caches calls without overrides", () => {
		const create = vi.fn(() => ({ value: crypto.randomUUID() }));
		const factory = createCachedFactory(create);

		expect(factory()).toBe(factory());
		expect(create).toHaveBeenCalledTimes(1);
	});

	it("returns fresh instances when overrides are provided", () => {
		const create = vi.fn(() => ({ value: crypto.randomUUID() }));
		const factory = createCachedFactory<object, { test?: boolean }>(create);

		expect(factory({ test: true })).not.toBe(factory({ test: true }));
		expect(create).toHaveBeenCalledTimes(2);
	});
});
`,
	},
	{
		relativePath: "tests/modules/users/use-cases/create-user.test.ts",
		content: `import { describe, expect, it, vi } from "vitest";
import type { UserRepository } from "@/modules/users";
import { createCreateUser } from "@/modules/users";

function createRepository(): UserRepository {
	return {
		create: vi.fn(),
		getById: vi.fn(),
		getByEmail: vi.fn(),
	};
}

describe("createCreateUser", () => {
	it("normalizes email through the domain schema before persisting", async () => {
		const repository = createRepository();
		const createdAt = new Date("2026-01-01T00:00:00.000Z");
		vi.mocked(repository.create).mockResolvedValue({
			id: "00000000-0000-4000-8000-000000000001" as never,
			name: "Ada",
			email: "ada@example.com" as never,
			createdAt,
		});
		const createUser = createCreateUser({ userRepository: repository });

		await expect(
			createUser({ name: " Ada ", email: "ada@example.com" }),
		).resolves.toMatchObject({ name: "Ada" });
		expect(repository.create).toHaveBeenCalledWith({
			name: "Ada",
			email: "ada@example.com",
		});
	});
});
`,
	},
	{
		relativePath: "tests/modules/users/use-cases/get-user-by-id.test.ts",
		content: `import { describe, expect, it, vi } from "vitest";
import type { UserRepository } from "@/modules/users";
import { asUserId, createGetUserById } from "@/modules/users";

function createRepository(): UserRepository {
	return {
		create: vi.fn(),
		getById: vi.fn(),
		getByEmail: vi.fn(),
	};
}

describe("createGetUserById", () => {
	it("throws a not-found error when no user exists", async () => {
		const repository = createRepository();
		vi.mocked(repository.getById).mockResolvedValue(undefined);
		const getUserById = createGetUserById({ userRepository: repository });

		await expect(
			getUserById(asUserId("00000000-0000-4000-8000-000000000001")),
		).rejects.toMatchObject({
			code: "not_found:user",
		});
	});
});
`,
	},
	{
		relativePath: "tests/modules/users/factory.test.ts",
		content: `import { describe, expect, it } from "vitest";
import { createUserUseCases } from "@/modules/users";

describe("createUserUseCases", () => {
	it("wires user use cases", () => {
		const useCases = createUserUseCases({
			userRepository: {
				create: async () => ({
					id: "00000000-0000-4000-8000-000000000001" as never,
					name: "Ada",
					email: "ada@example.com" as never,
					createdAt: new Date("2026-01-01T00:00:00.000Z"),
				}),
				getById: async () => undefined,
				getByEmail: async () => undefined,
			},
		});

		expect(useCases.createUser).toEqual(expect.any(Function));
		expect(useCases.getUserById).toEqual(expect.any(Function));
	});
});
`,
	},
	{
		relativePath: "tests/app/composition/users.test.ts",
		content: `import { describe, expect, it } from "vitest";
import { getUserUseCases } from "@/app/composition/users";

describe("getUserUseCases", () => {
	it("uses overrides to create isolated use case instances", () => {
		const first = getUserUseCases({
			userRepository: {
				create: async () => ({
					id: "00000000-0000-4000-8000-000000000001" as never,
					name: "Ada",
					email: "ada@example.com" as never,
					createdAt: new Date("2026-01-01T00:00:00.000Z"),
				}),
				getById: async () => undefined,
				getByEmail: async () => undefined,
			},
		});
		const second = getUserUseCases({
			userRepository: {
				create: async () => ({
					id: "00000000-0000-4000-8000-000000000002" as never,
					name: "Grace",
					email: "grace@example.com" as never,
					createdAt: new Date("2026-01-01T00:00:00.000Z"),
				}),
				getById: async () => undefined,
				getByEmail: async () => undefined,
			},
		});

		expect(first).not.toBe(second);
	});
});
`,
	},
];

export function createProductionCoreTemplateFiles(
	context: CoreTemplateContext,
): TemplateFile[] {
	return renderFiles(productionCoreTemplateFiles, coreTokens(context));
}
